// ─── World 3 — History (れきしのせかい) ────────────────────────────────────────

// ─── Module 3.1 — Then and Now (むかしといま) ──────────────────────────────────

export const m31 = {
  pool1: [
    {
      visual: '🕯️',
      q: 'むかし いえを てらすのに つかったのは？',
      qEn: 'What did people use to light their homes long ago?',
      choices: [{ jp: 'ろうそく', en: 'candle' }, { jp: 'でんきゅう', en: 'light bulb' }, { jp: 'でんとう', en: 'electric torch' }],
      correctJp: 'ろうそく',
    },
    {
      visual: '💡',
      q: 'いま いえを てらすのに つかうのは？',
      qEn: 'What do we use to light our homes today?',
      choices: [{ jp: 'でんきゅう', en: 'electric light' }, { jp: 'ろうそく', en: 'candle' }, { jp: 'たいまつ', en: 'torch' }],
      correctJp: 'でんきゅう',
    },
    {
      visual: '☎️',
      q: 'むかしの でんわの かたちは？',
      qEn: 'What did old telephones look like?',
      choices: [{ jp: 'まるい ダイヤルが あった', en: 'they had a round dial' }, { jp: 'タッチスクリーンだった', en: 'they had a touchscreen' }, { jp: 'カメラが あった', en: 'they had a camera' }],
      correctJp: 'まるい ダイヤルが あった',
    },
    {
      visual: '📱',
      q: 'いまの でんわを なんと よぶ？',
      qEn: 'What do we call modern phones?',
      choices: [{ jp: 'スマートフォン', en: 'smartphone' }, { jp: 'でんぽう', en: 'telegram' }, { jp: 'むせんき', en: 'wireless set' }],
      correctJp: 'スマートフォン',
    },
    {
      visual: '🐴',
      q: 'むかし ひとや にもつを はこんだのは？',
      qEn: 'What carried people and goods long ago?',
      choices: [{ jp: 'うまや ばしゃ', en: 'horse and carriage' }, { jp: 'じどうしゃ', en: 'car' }, { jp: 'ひこうき', en: 'aeroplane' }],
      correctJp: 'うまや ばしゃ',
    },
    {
      visual: '🚗',
      q: 'いま ひとや にもつを はこぶのは？',
      qEn: 'What carries people and goods today?',
      choices: [{ jp: 'じどうしゃ', en: 'car' }, { jp: 'うまや ばしゃ', en: 'horse and carriage' }, { jp: 'ふね', en: 'boat' }],
      correctJp: 'じどうしゃ',
    },
    {
      visual: '✉️',
      q: 'むかし ひとに メッセージを おくるには？',
      qEn: 'How did people send messages long ago?',
      choices: [{ jp: 'てがみ', en: 'letter' }, { jp: 'メール', en: 'email' }, { jp: 'メッセージアプリ', en: 'messaging app' }],
      correctJp: 'てがみ',
    },
    {
      visual: '💻',
      q: 'いま ひとに はやく メッセージを おくるには？',
      qEn: 'How do people send messages quickly today?',
      choices: [{ jp: 'メール', en: 'email' }, { jp: 'てがみ', en: 'letter' }, { jp: 'でんぽう', en: 'telegram' }],
      correctJp: 'メール',
    },
    {
      visual: '📺',
      q: 'むかしの テレビは どんな いろ？',
      qEn: 'What colour were old televisions?',
      choices: [{ jp: 'くろしろ', en: 'black and white' }, { jp: 'フルカラー', en: 'full colour' }, { jp: 'あかしろ', en: 'red and white' }],
      correctJp: 'くろしろ',
    },
    {
      visual: '🏫',
      q: 'むかしの がっこうで つかったのは？',
      qEn: 'What did children use to write at school long ago?',
      choices: [{ jp: 'スレートと チョーク', en: 'slate and chalk' }, { jp: 'タブレット', en: 'tablet' }, { jp: 'ボールペン', en: 'ballpoint pen' }],
      correctJp: 'スレートと チョーク',
    },
    {
      visual: '🚂',
      q: 'むかし ひとを はこんだ のりもの（きしゃ）を なんと いう？',
      qEn: 'What was an early train powered by?',
      choices: [{ jp: 'じょうき（スチーム）', en: 'steam' }, { jp: 'でんき', en: 'electricity' }, { jp: 'ガソリン', en: 'petrol' }],
      correctJp: 'じょうき（スチーム）',
    },
    {
      visual: '📰',
      q: 'むかし ニュースを しるには どうした？',
      qEn: 'How did people find out the news long ago?',
      choices: [{ jp: 'しんぶんを よんだ', en: 'read a newspaper' }, { jp: 'インターネットで しらべた', en: 'searched the internet' }, { jp: 'テレビを みた', en: 'watched TV' }],
      correctJp: 'しんぶんを よんだ',
    },
  ],
  pool2: [
    {
      visual: '⏳',
      q: 'ろうそくと でんきゅう、どちらが むかし？',
      qEn: 'Which came first, candles or electric lights?',
      choices: [{ jp: 'ろうそく', en: 'candles' }, { jp: 'でんきゅう', en: 'electric lights' }, { jp: 'どちらも おなじ', en: 'both the same' }],
      correctJp: 'ろうそく',
    },
    {
      visual: '🐴',
      q: 'うまと じどうしゃ、どちらが さきに つかわれた？',
      qEn: 'Which came first, horses or cars?',
      choices: [{ jp: 'うまや ばしゃ', en: 'horse and carriage' }, { jp: 'じどうしゃ', en: 'car' }, { jp: 'おなじ じだい', en: 'the same time' }],
      correctJp: 'うまや ばしゃ',
    },
    {
      visual: '✉️',
      q: 'てがみと メール、どちらが むかし？',
      qEn: 'Which is older, letters or email?',
      choices: [{ jp: 'てがみ', en: 'letter' }, { jp: 'メール', en: 'email' }, { jp: 'どちらも おなじ', en: 'both the same' }],
      correctJp: 'てがみ',
    },
    {
      visual: '🚂',
      q: 'きしゃと ひこうき、どちらが さきに つくられた？',
      qEn: 'Which was invented first, trains or aeroplanes?',
      choices: [{ jp: 'きしゃ', en: 'train' }, { jp: 'ひこうき', en: 'aeroplane' }, { jp: 'どちらも おなじ ころ', en: 'about the same time' }],
      correctJp: 'きしゃ',
    },
    {
      visual: '⏳',
      q: 'むかしと いまで かわった ものは どれ？',
      qEn: 'Which of these has changed from old to new?',
      choices: [{ jp: 'でんわ', en: 'telephone' }, { jp: 'たいよう', en: 'the sun' }, { jp: 'やま', en: 'mountains' }],
      correctJp: 'でんわ',
    },
    {
      visual: '🌟',
      q: 'むかしの こどもたちの あそびは？',
      qEn: 'How did children play long ago?',
      choices: [{ jp: 'そとで てを つかって あそんだ', en: 'played outside with their hands' }, { jp: 'テレビゲームを した', en: 'played video games' }, { jp: 'スマホを つかった', en: 'used smartphones' }],
      correctJp: 'そとで てを つかって あそんだ',
    },
    {
      visual: '💡',
      q: 'でんきゅうを はつめいしたのは だれ？',
      qEn: 'Who invented the electric light bulb?',
      choices: [{ jp: 'Thomas Edison', en: 'Thomas Edison' }, { jp: 'Neil Armstrong', en: 'Neil Armstrong' }, { jp: 'Florence Nightingale', en: 'Florence Nightingale' }],
      correctJp: 'Thomas Edison',
    },
    {
      visual: '📸',
      q: 'むかしの しゃしんは どんな いろ？',
      qEn: 'What colour were old photographs?',
      choices: [{ jp: 'くろしろ', en: 'black and white' }, { jp: 'フルカラー', en: 'full colour' }, { jp: 'あかいろ', en: 'red' }],
      correctJp: 'くろしろ',
    },
    {
      visual: '🏥',
      q: 'むかしの びょういんは いまと くらべて どうだった？',
      qEn: 'How were hospitals different long ago?',
      choices: [{ jp: 'きたなくて あぶなかった', en: 'unclean and dangerous' }, { jp: 'いまより きれいだった', en: 'cleaner than today' }, { jp: 'おなじだった', en: 'the same as today' }],
      correctJp: 'きたなくて あぶなかった',
    },
    {
      visual: '⏳',
      q: 'むかしの こどもたちは はたらいた？',
      qEn: 'Did children have to work long ago?',
      choices: [{ jp: 'はい、こうじょうで はたらいた', en: 'yes, they worked in factories' }, { jp: 'いいえ、がっこうに かよった', en: 'no, they went to school' }, { jp: 'いいえ、あそんでいた', en: 'no, they just played' }],
      correctJp: 'はい、こうじょうで はたらいた',
    },
    {
      visual: '🚀',
      q: 'この じゅんばんで ただしいのは？',
      qEn: 'Which order is correct — oldest to newest?',
      choices: [{ jp: 'ばしゃ → きしゃ → じどうしゃ', en: 'carriage → train → car' }, { jp: 'じどうしゃ → きしゃ → ばしゃ', en: 'car → train → carriage' }, { jp: 'きしゃ → ばしゃ → じどうしゃ', en: 'train → carriage → car' }],
      correctJp: 'ばしゃ → きしゃ → じどうしゃ',
    },
    {
      visual: '🌍',
      q: 'むかしは ちずが なかった。ひとは どうやって みちを しった？',
      qEn: 'Before maps existed, how did people find their way?',
      choices: [{ jp: 'ほしや たいようを みた', en: 'by stars and the sun' }, { jp: 'スマホを みた', en: 'used a smartphone' }, { jp: 'カーナビを つかった', en: 'used a sat-nav' }],
      correctJp: 'ほしや たいようを みた',
    },
  ],
}

// ─── Module 3.2 — Famous People (ゆうめいなひと) ──────────────────────────────

export const m32 = {
  pool1: [
    {
      visual: '🏥',
      q: 'かんごしを たいせつに して びょういんを よくした ひとは？',
      qEn: 'Who improved nursing and made hospitals safer?',
      choices: [{ jp: 'Florence Nightingale', en: 'Florence Nightingale' }, { jp: 'Amelia Earhart', en: 'Amelia Earhart' }, { jp: 'Mary Anning', en: 'Mary Anning' }],
      correctJp: 'Florence Nightingale',
    },
    {
      visual: '🌙',
      q: 'はじめて つきに たった ひとは？',
      qEn: 'Who was the first person to walk on the Moon?',
      choices: [{ jp: 'Neil Armstrong', en: 'Neil Armstrong' }, { jp: 'Isambard Kingdom Brunel', en: 'Isambard Kingdom Brunel' }, { jp: 'Rosa Parks', en: 'Rosa Parks' }],
      correctJp: 'Neil Armstrong',
    },
    {
      visual: '🦕',
      q: 'きょうりゅうの かせきを みつけた ひとは？',
      qEn: 'Who discovered dinosaur fossils?',
      choices: [{ jp: 'Mary Anning', en: 'Mary Anning' }, { jp: 'Florence Nightingale', en: 'Florence Nightingale' }, { jp: 'Neil Armstrong', en: 'Neil Armstrong' }],
      correctJp: 'Mary Anning',
    },
    {
      visual: '✊',
      q: 'バスで せきを ゆずらなかった ことで ゆうめいに なった ひとは？',
      qEn: 'Who became famous for refusing to give up her bus seat?',
      choices: [{ jp: 'Rosa Parks', en: 'Rosa Parks' }, { jp: 'Mary Anning', en: 'Mary Anning' }, { jp: 'Amelia Earhart', en: 'Amelia Earhart' }],
      correctJp: 'Rosa Parks',
    },
    {
      visual: '🌉',
      q: 'はしや てつどうを つくった えんじにあは？',
      qEn: 'Which famous engineer built bridges and railways?',
      choices: [{ jp: 'Isambard Kingdom Brunel', en: 'Isambard Kingdom Brunel' }, { jp: 'Neil Armstrong', en: 'Neil Armstrong' }, { jp: 'Florence Nightingale', en: 'Florence Nightingale' }],
      correctJp: 'Isambard Kingdom Brunel',
    },
    {
      visual: '✈️',
      q: 'はじめて ひとりで たいせいようを ひこうきで わたった じょせいは？',
      qEn: 'Who was the first woman to fly solo across the Atlantic?',
      choices: [{ jp: 'Amelia Earhart', en: 'Amelia Earhart' }, { jp: 'Rosa Parks', en: 'Rosa Parks' }, { jp: 'Mary Anning', en: 'Mary Anning' }],
      correctJp: 'Amelia Earhart',
    },
    {
      visual: '🏥',
      q: 'Florence Nightingale は なにを した？',
      qEn: 'What is Florence Nightingale famous for?',
      choices: [{ jp: 'かんごを よくした', en: 'improving nursing' }, { jp: 'つきに いった', en: 'going to the Moon' }, { jp: 'ひこうきで とんだ', en: 'flying an aeroplane' }],
      correctJp: 'かんごを よくした',
    },
    {
      visual: '🌙',
      q: 'Neil Armstrong が つきに いったのは？',
      qEn: 'When did Neil Armstrong go to the Moon?',
      choices: [{ jp: '1969ねん', en: '1969' }, { jp: '1066ねん', en: '1066' }, { jp: '1903ねん', en: '1903' }],
      correctJp: '1969ねん',
    },
    {
      visual: '🦕',
      q: 'Mary Anning は どこで かせきを みつけた？',
      qEn: 'Where did Mary Anning find fossils?',
      choices: [{ jp: 'かいがんで', en: 'on the coast' }, { jp: 'うちゅうで', en: 'in space' }, { jp: 'やまの うえで', en: 'on a mountain' }],
      correctJp: 'かいがんで',
    },
    {
      visual: '✊',
      q: 'Rosa Parks は なにを した？',
      qEn: 'What did Rosa Parks do?',
      choices: [{ jp: 'こうせいを もとめて たたかった', en: 'stood up for fairness' }, { jp: 'うちゅうに いった', en: 'went to space' }, { jp: 'はしを たてた', en: 'built a bridge' }],
      correctJp: 'こうせいを もとめて たたかった',
    },
    {
      visual: '🌉',
      q: 'Isambard Kingdom Brunel は なにで ゆうめい？',
      qEn: 'What is Brunel famous for?',
      choices: [{ jp: 'はしや てつどうを たてた', en: 'building bridges and railways' }, { jp: 'かんごを した', en: 'nursing' }, { jp: 'ひこうきを つくった', en: 'making aeroplanes' }],
      correctJp: 'はしや てつどうを たてた',
    },
    {
      visual: '✈️',
      q: 'Amelia Earhart は なにを した？',
      qEn: 'What is Amelia Earhart famous for?',
      choices: [{ jp: 'ひこうきで とんだ', en: 'flying an aeroplane' }, { jp: 'つきに いった', en: 'going to the Moon' }, { jp: 'かせきを みつけた', en: 'finding fossils' }],
      correctJp: 'ひこうきで とんだ',
    },
  ],
  pool2: [
    {
      visual: '🏥',
      q: 'Florence Nightingale が かんごしに おしえた いちばん たいせつな ことは？',
      qEn: 'What did Florence Nightingale teach nurses was most important?',
      choices: [{ jp: 'せいけつさ', en: 'cleanliness' }, { jp: 'すばやさ', en: 'speed' }, { jp: 'ちからつよさ', en: 'strength' }],
      correctJp: 'せいけつさ',
    },
    {
      visual: '🚀',
      q: 'Neil Armstrong が のった ロケットは？',
      qEn: 'What was the name of the mission that took Neil Armstrong to the Moon?',
      choices: [{ jp: 'Apollo 11', en: 'Apollo 11' }, { jp: 'Apollo 13', en: 'Apollo 13' }, { jp: 'Discovery 1', en: 'Discovery 1' }],
      correctJp: 'Apollo 11',
    },
    {
      visual: '🦕',
      q: 'Mary Anning が みつけた かせきは？',
      qEn: 'What type of fossil is Mary Anning famous for finding?',
      choices: [{ jp: 'イクチオサウルス（うみの きょうりゅう）', en: 'ichthyosaur (sea reptile)' }, { jp: 'ティラノサウルス', en: 'Tyrannosaurus Rex' }, { jp: 'マンモス', en: 'mammoth' }],
      correctJp: 'イクチオサウルス（うみの きょうりゅう）',
    },
    {
      visual: '✊',
      q: 'Rosa Parks は どこの くにの ひと？',
      qEn: 'Which country was Rosa Parks from?',
      choices: [{ jp: 'アメリカ', en: 'America' }, { jp: 'イギリス', en: 'Britain' }, { jp: 'フランス', en: 'France' }],
      correctJp: 'アメリカ',
    },
    {
      visual: '🌉',
      q: 'Brunel が つくった ゆうめいな はしは？',
      qEn: 'Which famous bridge did Brunel design?',
      choices: [{ jp: 'Clifton Suspension Bridge', en: 'Clifton Suspension Bridge' }, { jp: 'Tower Bridge', en: 'Tower Bridge' }, { jp: 'Golden Gate Bridge', en: 'Golden Gate Bridge' }],
      correctJp: 'Clifton Suspension Bridge',
    },
    {
      visual: '✈️',
      q: 'Amelia Earhart が わたった うみは？',
      qEn: 'Which ocean did Amelia Earhart fly across solo?',
      choices: [{ jp: 'たいせいよう', en: 'Atlantic Ocean' }, { jp: 'たいへいよう', en: 'Pacific Ocean' }, { jp: 'いんどよう', en: 'Indian Ocean' }],
      correctJp: 'たいせいよう',
    },
    {
      visual: '🏅',
      q: 'これらの ひとたちの きょうつうてんは？',
      qEn: 'What do all these famous people have in common?',
      choices: [{ jp: 'れきしに のこる ことを した', en: 'they did something historically important' }, { jp: 'すべて イギリスじん だった', en: 'they were all British' }, { jp: 'すべて かがくしゃ だった', en: 'they were all scientists' }],
      correctJp: 'れきしに のこる ことを した',
    },
    {
      visual: '🌙',
      q: 'つきに いった ひとは Neil Armstrong の ほかに だれが いる？',
      qEn: 'Who else walked on the Moon alongside Neil Armstrong?',
      choices: [{ jp: 'Buzz Aldrin', en: 'Buzz Aldrin' }, { jp: 'Amelia Earhart', en: 'Amelia Earhart' }, { jp: 'Isambard Kingdom Brunel', en: 'Isambard Kingdom Brunel' }],
      correctJp: 'Buzz Aldrin',
    },
    {
      visual: '🦕',
      q: 'かせきとは なに？',
      qEn: 'What is a fossil?',
      choices: [{ jp: 'いわに のこった むかしの いきものの あと', en: 'remains of ancient creatures in rock' }, { jp: 'あたらしい どうぶつの ほね', en: 'new animal bones' }, { jp: 'うちゅうの いし', en: 'a rock from space' }],
      correctJp: 'いわに のこった むかしの いきものの あと',
    },
    {
      visual: '🏥',
      q: 'Florence Nightingale は なんじだいの ひと？',
      qEn: 'In which century did Florence Nightingale live?',
      choices: [{ jp: '19せいき（1800ねんだい）', en: '19th century (1800s)' }, { jp: '20せいき（1900ねんだい）', en: '20th century (1900s)' }, { jp: '21せいき（2000ねんだい）', en: '21st century (2000s)' }],
      correctJp: '19せいき（1800ねんだい）',
    },
    {
      visual: '✊',
      q: 'Rosa Parks が したことは どんな いみが あった？',
      qEn: 'Why was what Rosa Parks did so important?',
      choices: [{ jp: 'みんな びょうどうに あつかわれるべき と しめした', en: 'she showed everyone deserves equal treatment' }, { jp: 'あたらしい のりものを つくった', en: 'she invented a new vehicle' }, { jp: 'かがくを すすめた', en: 'she advanced science' }],
      correctJp: 'みんな びょうどうに あつかわれるべき と しめした',
    },
    {
      visual: '🌟',
      q: 'ゆうめいなひとの たんじょうびを きろくする ために なにを つかう？',
      qEn: 'What do we use to record when famous people were born?',
      choices: [{ jp: 'ねんぴょう', en: 'timeline' }, { jp: 'ちず', en: 'map' }, { jp: 'えほん', en: 'picture book' }],
      correctJp: 'ねんぴょう',
    },
  ],
}

// ─── Module 3.3 — Important Events (おおきなできごと) ─────────────────────────

export const m33 = {
  pool1: [
    {
      visual: '🔥',
      q: 'ロンドンの おおかじは いつ おきた？',
      qEn: 'When did the Great Fire of London happen?',
      choices: [{ jp: '1666ねん', en: '1666' }, { jp: '1969ねん', en: '1969' }, { jp: '1903ねん', en: '1903' }],
      correctJp: '1666ねん',
    },
    {
      visual: '🔥',
      q: 'ロンドンの おおかじで もえたのは？',
      qEn: 'What did the Great Fire of London burn down?',
      choices: [{ jp: 'たくさんの いえや たてもの', en: 'thousands of houses and buildings' }, { jp: 'やまや もり', en: 'mountains and forests' }, { jp: 'うみ', en: 'the sea' }],
      correctJp: 'たくさんの いえや たてもの',
    },
    {
      visual: '🔥',
      q: 'ロンドンの おおかじは どこから はじまった？',
      qEn: 'Where did the Great Fire of London start?',
      choices: [{ jp: 'パン やさん', en: 'a bakery' }, { jp: 'きゅうでん', en: 'a palace' }, { jp: 'がっこう', en: 'a school' }],
      correctJp: 'パン やさん',
    },
    {
      visual: '✈️',
      q: 'はじめて ひこうきを とばしたのは だれ？',
      qEn: 'Who made the first successful aeroplane flight?',
      choices: [{ jp: 'Wright Brothers', en: 'Wright Brothers' }, { jp: 'Neil Armstrong', en: 'Neil Armstrong' }, { jp: 'Brunel', en: 'Brunel' }],
      correctJp: 'Wright Brothers',
    },
    {
      visual: '✈️',
      q: 'はじめての ひこうきとびは いつ？',
      qEn: 'When was the first aeroplane flight?',
      choices: [{ jp: '1903ねん', en: '1903' }, { jp: '1666ねん', en: '1666' }, { jp: '1969ねん', en: '1969' }],
      correctJp: '1903ねん',
    },
    {
      visual: '🌙',
      q: 'はじめて つきに いったのは いつ？',
      qEn: 'When did humans first land on the Moon?',
      choices: [{ jp: '1969ねん', en: '1969' }, { jp: '1903ねん', en: '1903' }, { jp: '1666ねん', en: '1666' }],
      correctJp: '1969ねん',
    },
    {
      visual: '🌙',
      q: 'つきに はじめて いったひとは だれ？',
      qEn: 'Who was the first person on the Moon?',
      choices: [{ jp: 'Neil Armstrong', en: 'Neil Armstrong' }, { jp: 'Wright Brothers', en: 'Wright Brothers' }, { jp: 'Brunel', en: 'Brunel' }],
      correctJp: 'Neil Armstrong',
    },
    {
      visual: '🔥',
      q: 'ロンドンの おおかじの あと、にほんの たてものは なにで つくられた？',
      qEn: 'After the Great Fire, what were London buildings made from instead of wood?',
      choices: [{ jp: 'れんが', en: 'brick' }, { jp: 'プラスチック', en: 'plastic' }, { jp: 'ガラス', en: 'glass' }],
      correctJp: 'れんが',
    },
    {
      visual: '⏳',
      q: 'おおかじ・ひこうきとび・つきへ — この じゅんばんで あっている？',
      qEn: 'Great Fire, aeroplane flight, Moon landing — is this the correct order?',
      choices: [{ jp: 'はい、あっている', en: 'yes, correct order' }, { jp: 'いいえ、ちがう', en: 'no, wrong order' }, { jp: 'すべて おなじ とし', en: 'all the same year' }],
      correctJp: 'はい、あっている',
    },
    {
      visual: '🚂',
      q: 'さいしょの じょうききしゃは いつ できた？',
      qEn: 'When was the first steam railway?',
      choices: [{ jp: '1800ねんだい はじめ', en: 'early 1800s' }, { jp: '1600ねんだい', en: '1600s' }, { jp: '1900ねんだい おわり', en: 'late 1900s' }],
      correctJp: '1800ねんだい はじめ',
    },
    {
      visual: '🌍',
      q: 'つきいちの おおきな できごとを ならべる ために なにを つかう？',
      qEn: 'What do we use to put historical events in order?',
      choices: [{ jp: 'ねんぴょう', en: 'a timeline' }, { jp: 'ちず', en: 'a map' }, { jp: 'えほん', en: 'a picture book' }],
      correctJp: 'ねんぴょう',
    },
    {
      visual: '🔥',
      q: 'ロンドンの おおかじは なんにちつづいた？',
      qEn: 'How many days did the Great Fire of London last?',
      choices: [{ jp: 'よっかかん', en: 'four days' }, { jp: 'いちにち', en: 'one day' }, { jp: 'いっかげつ', en: 'one month' }],
      correctJp: 'よっかかん',
    },
  ],
  pool2: [
    {
      visual: '⏳',
      q: 'ロンドンの おおかじ と ひこうきの はじめての とびかた、どちらが さき？',
      qEn: 'Which came first, the Great Fire of London or the first aeroplane flight?',
      choices: [{ jp: 'ロンドンの おおかじ（1666）', en: 'Great Fire of London (1666)' }, { jp: 'ひこうきの とびかた（1903）', en: 'first aeroplane flight (1903)' }, { jp: 'おなじ とし', en: 'same year' }],
      correctJp: 'ロンドンの おおかじ（1666）',
    },
    {
      visual: '⏳',
      q: 'ひこうきの はじめての とびかた と つきへの ちゃくりく、どちらが さき？',
      qEn: 'Which happened first, the first aeroplane flight or the Moon landing?',
      choices: [{ jp: 'ひこうきの はじめての とびかた（1903）', en: 'first aeroplane flight (1903)' }, { jp: 'つきへの ちゃくりく（1969）', en: 'Moon landing (1969)' }, { jp: 'おなじ とし', en: 'same year' }],
      correctJp: 'ひこうきの はじめての とびかた（1903）',
    },
    {
      visual: '🌙',
      q: 'つきいちの ちゃくりくで つかった のりものは？',
      qEn: 'What vehicle landed on the Moon in 1969?',
      choices: [{ jp: 'ロケット と つきちゃくりくせん', en: 'rocket and lunar module' }, { jp: 'ひこうき', en: 'aeroplane' }, { jp: 'うみのふね', en: 'ship' }],
      correctJp: 'ロケット と つきちゃくりくせん',
    },
    {
      visual: '🔥',
      q: 'ロンドンの おおかじで なんにんが いえを うしなった？',
      qEn: 'How many people lost their homes in the Great Fire of London?',
      choices: [{ jp: 'やく 70,000にん', en: 'about 70,000 people' }, { jp: 'やく 10にん', en: 'about 10 people' }, { jp: 'だれも うしなわなかった', en: 'nobody lost their home' }],
      correctJp: 'やく 70,000にん',
    },
    {
      visual: '✈️',
      q: 'Wright Brothers の さいしょの ひこうは なんびょう だった？',
      qEn: 'How long was the Wright Brothers first flight?',
      choices: [{ jp: 'やく 12びょう', en: 'about 12 seconds' }, { jp: 'やく 1じかん', en: 'about 1 hour' }, { jp: 'やく 1ぷん', en: 'about 1 minute' }],
      correctJp: 'やく 12びょう',
    },
    {
      visual: '🚀',
      q: 'つきに いく ために なんにち かかった？',
      qEn: 'How many days did it take to travel to the Moon?',
      choices: [{ jp: 'やく 3にち', en: 'about 3 days' }, { jp: 'やく 1ねん', en: 'about 1 year' }, { jp: 'やく 1じかん', en: 'about 1 hour' }],
      correctJp: 'やく 3にち',
    },
    {
      visual: '⏳',
      q: 'むかしの できごとを しるための しりょうは？',
      qEn: 'Where can we find out about historical events?',
      choices: [{ jp: 'ほん、しゃしん、えなど', en: 'books, photos, pictures etc.' }, { jp: 'スマートフォン だけ', en: 'only smartphones' }, { jp: 'なにも しらべられない', en: 'we cannot find out' }],
      correctJp: 'ほん、しゃしん、えなど',
    },
    {
      visual: '🌍',
      q: 'れきしは なぜ まなぶの？',
      qEn: 'Why do we learn about history?',
      choices: [{ jp: 'むかしから まなび みらいに いかす ため', en: 'to learn from the past for the future' }, { jp: 'たいくつだから', en: 'because it is boring' }, { jp: 'いみが ない', en: 'it has no meaning' }],
      correctJp: 'むかしから まなび みらいに いかす ため',
    },
    {
      visual: '🔥',
      q: 'ロンドンの おおかじの あとに たてられた ゆうめいな たてものは？',
      qEn: 'Which famous building was rebuilt after the Great Fire of London?',
      choices: [{ jp: 'St Paul\'s Cathedral', en: 'St Paul\'s Cathedral' }, { jp: 'Tower Bridge', en: 'Tower Bridge' }, { jp: 'Buckingham Palace', en: 'Buckingham Palace' }],
      correctJp: 'St Paul\'s Cathedral',
    },
    {
      visual: '🌟',
      q: 'むかしの できごとを まなぶ がくもんは？',
      qEn: 'What is the subject called where we study past events?',
      choices: [{ jp: 'れきし', en: 'history' }, { jp: 'ちり', en: 'geography' }, { jp: 'かがく', en: 'science' }],
      correctJp: 'れきし',
    },
    {
      visual: '⏳',
      q: 'さいしょの ひこうき、おおかじ、つきちゃくりくを ふるい じゅんに ならべると？',
      qEn: 'Put these in order oldest first: aeroplane, Great Fire, Moon landing',
      choices: [{ jp: 'おおかじ → ひこうき → つきちゃくりく', en: 'Great Fire → aeroplane → Moon landing' }, { jp: 'ひこうき → おおかじ → つきちゃくりく', en: 'aeroplane → Great Fire → Moon landing' }, { jp: 'つきちゃくりく → おおかじ → ひこうき', en: 'Moon landing → Great Fire → aeroplane' }],
      correctJp: 'おおかじ → ひこうき → つきちゃくりく',
    },
    {
      visual: '🚂',
      q: 'てつどうが できて ひとびとの せいかつは どう かわった？',
      qEn: 'How did railways change people\'s lives?',
      choices: [{ jp: 'とおい ところへ はやく いけるように なった', en: 'people could travel far away much faster' }, { jp: 'なにも かわらなかった', en: 'nothing changed' }, { jp: 'もっと あるく ように なった', en: 'people walked more' }],
      correctJp: 'とおい ところへ はやく いけるように なった',
    },
  ],
}

// ─── World 3 module registry ──────────────────────────────────────────────────

export const WORLD3_MODULES = [
  { id: 1, titleJp: 'むかしといまをくらべよう', titleEn: 'Then and Now',     emoji: '⏳', color: '#E8963E', data: m31 },
  { id: 2, titleJp: 'ゆうめいなひとをしろう',   titleEn: 'Famous People',    emoji: '🌟', color: '#6BAF6B', data: m32 },
  { id: 3, titleJp: 'おおきなできごとをしろう', titleEn: 'Important Events', emoji: '🔥', color: '#D45B5B', data: m33 },
]
