// ─── World 4 — Art and Design (アートのせかい) ─────────────────────────────────

// ─── Module 4.1 — Colours and Mixing (いろ) ────────────────────────────────────

export const m41 = {
  pool1: [
    {
      visual: '🔴🔵🟡',
      q: 'げんしょくは どれ？（みっつ えらんで）',
      qEn: 'Which are the three primary colours?',
      choices: [{ jp: 'あか・あお・き', en: 'red, blue, yellow' }, { jp: 'みどり・むらさき・オレンジ', en: 'green, purple, orange' }, { jp: 'くろ・しろ・はいいろ', en: 'black, white, grey' }],
      correctJp: 'あか・あお・き',
    },
    {
      visual: '🔴',
      q: 'この いろの なまえは？',
      qEn: 'What is this colour called?',
      choices: [{ jp: 'あか', en: 'red' }, { jp: 'あお', en: 'blue' }, { jp: 'き', en: 'yellow' }],
      correctJp: 'あか',
    },
    {
      visual: '🔵',
      q: 'この いろの なまえは？',
      qEn: 'What is this colour called?',
      choices: [{ jp: 'あお', en: 'blue' }, { jp: 'みどり', en: 'green' }, { jp: 'むらさき', en: 'purple' }],
      correctJp: 'あお',
    },
    {
      visual: '🟡',
      q: 'この いろの なまえは？',
      qEn: 'What is this colour called?',
      choices: [{ jp: 'き', en: 'yellow' }, { jp: 'オレンジ', en: 'orange' }, { jp: 'みどり', en: 'green' }],
      correctJp: 'き',
    },
    {
      visual: '🟢',
      q: 'みどりは げんしょく？',
      qEn: 'Is green a primary colour?',
      choices: [{ jp: 'いいえ、まぜてつくる', en: 'no, it is mixed' }, { jp: 'はい、げんしょく', en: 'yes, it is primary' }, { jp: 'わからない', en: 'I don\'t know' }],
      correctJp: 'いいえ、まぜてつくる',
    },
    {
      visual: '🌈',
      q: 'にじに あかは ある？',
      qEn: 'Is red in a rainbow?',
      choices: [{ jp: 'はい', en: 'yes' }, { jp: 'いいえ', en: 'no' }, { jp: 'ときどき', en: 'sometimes' }],
      correctJp: 'はい',
    },
    {
      visual: '🎨',
      q: 'えのぐの みっつの げんしょくは？',
      qEn: 'What are the three primary paint colours?',
      choices: [{ jp: 'あか・あお・き', en: 'red, blue, yellow' }, { jp: 'みどり・むらさき・オレンジ', en: 'green, purple, orange' }, { jp: 'しろ・くろ・はいいろ', en: 'white, black, grey' }],
      correctJp: 'あか・あお・き',
    },
    {
      visual: '⬛⬜',
      q: 'くろと しろを まぜると？',
      qEn: 'What colour do you get when you mix black and white?',
      choices: [{ jp: 'はいいろ', en: 'grey' }, { jp: 'むらさき', en: 'purple' }, { jp: 'みどり', en: 'green' }],
      correctJp: 'はいいろ',
    },
    {
      visual: '🎨',
      q: 'いろを まったく まぜないと どんな いろ？',
      qEn: 'Which colour has no other colours mixed in?',
      choices: [{ jp: 'げんしょく', en: 'primary colour' }, { jp: 'まぜいろ', en: 'mixed colour' }, { jp: 'にじのいろ', en: 'rainbow colour' }],
      correctJp: 'げんしょく',
    },
    {
      visual: '🖌️',
      q: 'しろに あかを まぜると？',
      qEn: 'What colour do you get when you mix white and red?',
      choices: [{ jp: 'ピンク', en: 'pink' }, { jp: 'オレンジ', en: 'orange' }, { jp: 'むらさき', en: 'purple' }],
      correctJp: 'ピンク',
    },
    {
      visual: '🌊',
      q: 'うみのような つめたい かんじの いろは？',
      qEn: 'Which colour feels cold like the ocean?',
      choices: [{ jp: 'あお', en: 'blue' }, { jp: 'あか', en: 'red' }, { jp: 'オレンジ', en: 'orange' }],
      correctJp: 'あお',
    },
    {
      visual: '🔥',
      q: 'ひのような あたたかい かんじの いろは？',
      qEn: 'Which colour feels warm like fire?',
      choices: [{ jp: 'あか', en: 'red' }, { jp: 'あお', en: 'blue' }, { jp: 'みどり', en: 'green' }],
      correctJp: 'あか',
    },
  ],
  pool2: [
    {
      visual: '🔴🔵',
      q: 'あか と あお を まぜると？',
      qEn: 'What colour do you get when you mix red and blue?',
      choices: [{ jp: 'むらさき', en: 'purple' }, { jp: 'オレンジ', en: 'orange' }, { jp: 'みどり', en: 'green' }],
      correctJp: 'むらさき',
    },
    {
      visual: '🔴🟡',
      q: 'あか と き を まぜると？',
      qEn: 'What colour do you get when you mix red and yellow?',
      choices: [{ jp: 'オレンジ', en: 'orange' }, { jp: 'みどり', en: 'green' }, { jp: 'むらさき', en: 'purple' }],
      correctJp: 'オレンジ',
    },
    {
      visual: '🔵🟡',
      q: 'あお と き を まぜると？',
      qEn: 'What colour do you get when you mix blue and yellow?',
      choices: [{ jp: 'みどり', en: 'green' }, { jp: 'むらさき', en: 'purple' }, { jp: 'オレンジ', en: 'orange' }],
      correctJp: 'みどり',
    },
    {
      visual: '🔥🌅',
      q: 'あたたかい いろの なかまは どれ？',
      qEn: 'Which group are the warm colours?',
      choices: [{ jp: 'あか・オレンジ・き', en: 'red, orange, yellow' }, { jp: 'あお・みどり・むらさき', en: 'blue, green, purple' }, { jp: 'しろ・くろ・はいいろ', en: 'white, black, grey' }],
      correctJp: 'あか・オレンジ・き',
    },
    {
      visual: '🌊❄️',
      q: 'つめたい いろの なかまは どれ？',
      qEn: 'Which group are the cool colours?',
      choices: [{ jp: 'あお・みどり・むらさき', en: 'blue, green, purple' }, { jp: 'あか・オレンジ・き', en: 'red, orange, yellow' }, { jp: 'しろ・くろ・はいいろ', en: 'white, black, grey' }],
      correctJp: 'あお・みどり・むらさき',
    },
    {
      visual: '🟠',
      q: 'オレンジは なに いろを まぜて つくる？',
      qEn: 'What colours make orange?',
      choices: [{ jp: 'あか と き', en: 'red and yellow' }, { jp: 'あか と あお', en: 'red and blue' }, { jp: 'あお と き', en: 'blue and yellow' }],
      correctJp: 'あか と き',
    },
    {
      visual: '🟣',
      q: 'むらさきは なに いろを まぜて つくる？',
      qEn: 'What colours make purple?',
      choices: [{ jp: 'あか と あお', en: 'red and blue' }, { jp: 'あか と き', en: 'red and yellow' }, { jp: 'あお と き', en: 'blue and yellow' }],
      correctJp: 'あか と あお',
    },
    {
      visual: '🌿',
      q: 'みどりは なに いろを まぜて つくる？',
      qEn: 'What colours make green?',
      choices: [{ jp: 'あお と き', en: 'blue and yellow' }, { jp: 'あか と き', en: 'red and yellow' }, { jp: 'あか と あお', en: 'red and blue' }],
      correctJp: 'あお と き',
    },
    {
      visual: '🎨',
      q: 'げんしょくを ぜんぶ まぜると？',
      qEn: 'What do you get when you mix all primary colours together?',
      choices: [{ jp: 'ちゃいろや くろっぽい いろ', en: 'brown or dark muddy colour' }, { jp: 'しろ', en: 'white' }, { jp: 'にじいろ', en: 'rainbow colours' }],
      correctJp: 'ちゃいろや くろっぽい いろ',
    },
    {
      visual: '🌅',
      q: 'にちぼつの そらの いろに ちかいのは？',
      qEn: 'Which colour is closest to a sunset sky?',
      choices: [{ jp: 'オレンジ', en: 'orange' }, { jp: 'あお', en: 'blue' }, { jp: 'みどり', en: 'green' }],
      correctJp: 'オレンジ',
    },
    {
      visual: '🖌️',
      q: 'きいろに あおを まぜると なに いろに なる？',
      qEn: 'What happens when you mix yellow and blue paint?',
      choices: [{ jp: 'みどり', en: 'green' }, { jp: 'オレンジ', en: 'orange' }, { jp: 'むらさき', en: 'purple' }],
      correctJp: 'みどり',
    },
    {
      visual: '🎨',
      q: 'まぜて つくった いろを なんと よぶ？',
      qEn: 'Colours made by mixing two primary colours are called...?',
      choices: [{ jp: 'にじしょく（secondary colours）', en: 'secondary colours' }, { jp: 'げんしょく（primary colours）', en: 'primary colours' }, { jp: 'あたたかい いろ', en: 'warm colours' }],
      correctJp: 'にじしょく（secondary colours）',
    },
  ],
}

// ─── Module 4.2 — Patterns and Shapes in Art (もよう) ─────────────────────────

export const m42 = {
  pool1: [
    {
      visual: '〰️',
      q: 'なみなみ した せんを なんと いう？',
      qEn: 'What do we call a wavy line?',
      choices: [{ jp: 'なみがた', en: 'wavy' }, { jp: 'まっすぐ', en: 'straight' }, { jp: 'ざぐざぐ', en: 'zigzag' }],
      correctJp: 'なみがた',
    },
    {
      visual: '📏',
      q: 'まっすぐな せんを なんと いう？',
      qEn: 'What do we call a perfectly straight line?',
      choices: [{ jp: 'ちょくせん', en: 'straight line' }, { jp: 'なみがた', en: 'wavy line' }, { jp: 'ざぐざぐ', en: 'zigzag' }],
      correctJp: 'ちょくせん',
    },
    {
      visual: '⚡',
      q: 'ざぐざぐな せんを なんと いう？',
      qEn: 'What do we call a zigzag line?',
      choices: [{ jp: 'ざぐざぐ', en: 'zigzag' }, { jp: 'なみがた', en: 'wavy' }, { jp: 'まる', en: 'circle' }],
      correctJp: 'ざぐざぐ',
    },
    {
      visual: '🟥🟦🟥🟦',
      q: 'このもようの なまえは？（たてがわの しましも）',
      qEn: 'What is this pattern called? (alternating coloured stripes)',
      choices: [{ jp: 'しましも', en: 'stripes' }, { jp: 'みずたま', en: 'spots/dots' }, { jp: 'チェック', en: 'checkerboard' }],
      correctJp: 'しましも',
    },
    {
      visual: '🔴⚪🔴⚪',
      q: 'まるい てんてんの もようを なんと いう？',
      qEn: 'What is a pattern of round dots called?',
      choices: [{ jp: 'みずたま', en: 'polka dots' }, { jp: 'しましも', en: 'stripes' }, { jp: 'ざぐざぐ', en: 'zigzag' }],
      correctJp: 'みずたま',
    },
    {
      visual: '♟️',
      q: 'チェス ばんのような もようを なんと いう？',
      qEn: 'What is a chessboard-style pattern called?',
      choices: [{ jp: 'チェック', en: 'checkerboard' }, { jp: 'しましも', en: 'stripes' }, { jp: 'みずたま', en: 'polka dots' }],
      correctJp: 'チェック',
    },
    {
      visual: '🌸🌸🌸',
      q: 'くりかえす もようを なんと いう？',
      qEn: 'What do we call a pattern that repeats?',
      choices: [{ jp: 'はんぷく もよう', en: 'repeating pattern' }, { jp: 'ランダム', en: 'random' }, { jp: 'いちど だけ', en: 'once only' }],
      correctJp: 'はんぷく もよう',
    },
    {
      visual: '⬛⬜⬛⬜',
      q: 'このもようは なに いろを つかっている？',
      qEn: 'What colours are used in this pattern?',
      choices: [{ jp: 'くろと しろ', en: 'black and white' }, { jp: 'あかと あお', en: 'red and blue' }, { jp: 'みどりと き', en: 'green and yellow' }],
      correctJp: 'くろと しろ',
    },
    {
      visual: '🔺🔻🔺🔻',
      q: 'このもようの つぎは なに？（△▽△▽...）',
      qEn: 'What comes next in this pattern? (△▽△▽...)',
      choices: [{ jp: '△', en: 'triangle pointing up' }, { jp: '○', en: 'circle' }, { jp: '□', en: 'square' }],
      correctJp: '△',
    },
    {
      visual: '🎨',
      q: 'アートで もようを つくる せんのしゅるいは？',
      qEn: 'Which types of lines can create patterns in art?',
      choices: [{ jp: 'ちょくせん・なみ・ざぐざぐ など', en: 'straight, wavy, zigzag etc.' }, { jp: 'ちょくせん だけ', en: 'only straight' }, { jp: 'なみ だけ', en: 'only wavy' }],
      correctJp: 'ちょくせん・なみ・ざぐざぐ など',
    },
    {
      visual: '🌀',
      q: 'くるくると まいた せんを なんと いう？',
      qEn: 'What do we call a spiral line?',
      choices: [{ jp: 'うずまき', en: 'spiral' }, { jp: 'ざぐざぐ', en: 'zigzag' }, { jp: 'ちょくせん', en: 'straight line' }],
      correctJp: 'うずまき',
    },
    {
      visual: '🔶🔷🔶🔷',
      q: 'このもようの つぎは なに？（◆◇◆◇...）',
      qEn: 'What comes next in this pattern? (◆◇◆◇...)',
      choices: [{ jp: '◆', en: 'orange diamond' }, { jp: '○', en: 'circle' }, { jp: '★', en: 'star' }],
      correctJp: '◆',
    },
  ],
  pool2: [
    {
      visual: '🔴🟡🟢🔴🟡',
      q: 'このもようの つぎは なに？（🔴🟡🟢🔴🟡...）',
      qEn: 'What comes next? (red, yellow, green, red, yellow...)',
      choices: [{ jp: '🟢 みどり', en: 'green' }, { jp: '🔴 あか', en: 'red' }, { jp: '🟡 き', en: 'yellow' }],
      correctJp: '🟢 みどり',
    },
    {
      visual: '⭐🌙⭐⭐🌙⭐',
      q: 'このもようの つぎは なに？（⭐🌙⭐⭐🌙⭐...）',
      qEn: 'What comes next? (star, moon, star, star, moon, star...)',
      choices: [{ jp: '⭐ ほし', en: 'star' }, { jp: '🌙 つき', en: 'moon' }, { jp: '☀️ たいよう', en: 'sun' }],
      correctJp: '⭐ ほし',
    },
    {
      visual: '🐱🐶🐱🐶',
      q: 'このもようの つぎは なに？（ねこ・いぬ・ねこ・いぬ...）',
      qEn: 'What comes next? (cat, dog, cat, dog...)',
      choices: [{ jp: '🐱 ねこ', en: 'cat' }, { jp: '🐶 いぬ', en: 'dog' }, { jp: '🐦 とり', en: 'bird' }],
      correctJp: '🐱 ねこ',
    },
    {
      visual: '🎨',
      q: 'しましもの もようは どうやって つくる？',
      qEn: 'How do you make a striped pattern?',
      choices: [{ jp: 'すじを くりかえす', en: 'repeat stripes' }, { jp: 'まるを かく', en: 'draw circles' }, { jp: 'ランダムに てんを うつ', en: 'put dots randomly' }],
      correctJp: 'すじを くりかえす',
    },
    {
      visual: '🔵🟡🔵🟡🔵',
      q: 'このもようの つぎは なに？（あお・き・あお・き・あお...）',
      qEn: 'What comes next? (blue, yellow, blue, yellow, blue...)',
      choices: [{ jp: '🟡 き', en: 'yellow' }, { jp: '🔵 あお', en: 'blue' }, { jp: '🟢 みどり', en: 'green' }],
      correctJp: '🟡 き',
    },
    {
      visual: '🌸🌺🌸🌺',
      q: 'このもようで つかっている かたちは？',
      qEn: 'What shapes are used in this pattern?',
      choices: [{ jp: 'さくら と バラ', en: 'cherry blossom and rose' }, { jp: 'ほし と つき', en: 'star and moon' }, { jp: 'まる と しかく', en: 'circle and square' }],
      correctJp: 'さくら と バラ',
    },
    {
      visual: '♟️',
      q: 'チェックもようは なんかいで くりかえす？',
      qEn: 'How often does a checkerboard pattern repeat?',
      choices: [{ jp: '2つ ごとに', en: 'every 2 squares' }, { jp: '5つ ごとに', en: 'every 5 squares' }, { jp: 'くりかえさない', en: 'it does not repeat' }],
      correctJp: '2つ ごとに',
    },
    {
      visual: '🎨',
      q: 'アーティストが もようを つくる りゆうは？',
      qEn: 'Why do artists create patterns?',
      choices: [{ jp: 'きれいに するため、かんじょうを あらわすため', en: 'to make things beautiful and express feelings' }, { jp: 'ただ ひまだから', en: 'just because they are bored' }, { jp: 'みんなが おなじ に なるため', en: 'to make everything the same' }],
      correctJp: 'きれいに するため、かんじょうを あらわすため',
    },
    {
      visual: '🔴🔴🔵🔴🔴🔵',
      q: 'このもようの つぎは なに？（🔴🔴🔵🔴🔴🔵...）',
      qEn: 'What comes next? (red, red, blue, red, red, blue...)',
      choices: [{ jp: '🔴 あか', en: 'red' }, { jp: '🔵 あお', en: 'blue' }, { jp: '🟡 き', en: 'yellow' }],
      correctJp: '🔴 あか',
    },
    {
      visual: '🌀',
      q: 'うずまきの もようを つかう アーティストは？',
      qEn: 'Which artist is famous for using spiral and dot patterns?',
      choices: [{ jp: 'Yayoi Kusama', en: 'Yayoi Kusama' }, { jp: 'Piet Mondrian', en: 'Piet Mondrian' }, { jp: 'Claude Monet', en: 'Claude Monet' }],
      correctJp: 'Yayoi Kusama',
    },
    {
      visual: '⭐🔵⭐🔵⭐🔵',
      q: 'このもようの きまりは？',
      qEn: 'What is the rule for this pattern?',
      choices: [{ jp: 'ほし と あお が こうごに くりかえす', en: 'star and blue alternate' }, { jp: 'ほし が ふえる', en: 'stars increase' }, { jp: 'きまりは ない', en: 'no rule' }],
      correctJp: 'ほし と あお が こうごに くりかえす',
    },
    {
      visual: '🎭',
      q: 'もようを なにかに くりかえし つかうことを なんと いう？',
      qEn: 'Using a shape or image repeated across a surface is called...?',
      choices: [{ jp: 'パターン', en: 'a pattern' }, { jp: 'ちょうこく', en: 'a sculpture' }, { jp: 'スケッチ', en: 'a sketch' }],
      correctJp: 'パターン',
    },
  ],
}

// ─── Module 4.3 — Famous Art (ゆうめいなアート) ────────────────────────────────

export const m43 = {
  pool1: [
    {
      visual: '🟥🟦🟨',
      q: 'たての まっすぐな せん と げんしょくの ます。このスタイルの アーティストは？',
      qEn: 'Straight grid lines with blocks of primary colour — which artist made this style?',
      choices: [{ jp: 'Piet Mondrian', en: 'Piet Mondrian' }, { jp: 'Claude Monet', en: 'Claude Monet' }, { jp: 'Yayoi Kusama', en: 'Yayoi Kusama' }],
      correctJp: 'Piet Mondrian',
    },
    {
      visual: '🌸💧',
      q: 'やわらかい いろで しぜんや みずを えがいた アーティストは？',
      qEn: 'Which artist painted soft coloured scenes of nature and water?',
      choices: [{ jp: 'Claude Monet', en: 'Claude Monet' }, { jp: 'Piet Mondrian', en: 'Piet Mondrian' }, { jp: 'Andy Goldsworthy', en: 'Andy Goldsworthy' }],
      correctJp: 'Claude Monet',
    },
    {
      visual: '🔴⚪🔴⚪',
      q: 'てんてんの もようで ゆうめいな アーティストは？',
      qEn: 'Which artist is famous for polka dot patterns?',
      choices: [{ jp: 'Yayoi Kusama', en: 'Yayoi Kusama' }, { jp: 'Claude Monet', en: 'Claude Monet' }, { jp: 'Piet Mondrian', en: 'Piet Mondrian' }],
      correctJp: 'Yayoi Kusama',
    },
    {
      visual: '🍂🪨',
      q: 'しぜんの ものをつかって そとで アートを つくった アーティストは？',
      qEn: 'Which artist uses natural materials to create outdoor art?',
      choices: [{ jp: 'Andy Goldsworthy', en: 'Andy Goldsworthy' }, { jp: 'Yayoi Kusama', en: 'Yayoi Kusama' }, { jp: 'Piet Mondrian', en: 'Piet Mondrian' }],
      correctJp: 'Andy Goldsworthy',
    },
    {
      visual: '🌀🔴🟡',
      q: 'てんてんで ものがたりを つたえる でんとうてきな アートは？',
      qEn: 'Which traditional art uses dots to tell stories?',
      choices: [{ jp: 'オーストラリアの アボリジナル アート', en: 'Australian Aboriginal dot art' }, { jp: 'ヨーロッパの かいが', en: 'European painting' }, { jp: 'にほんの まんが', en: 'Japanese manga' }],
      correctJp: 'オーストラリアの アボリジナル アート',
    },
    {
      visual: '🟥🟦🟨',
      q: 'Mondrian の えで よく つかわれる いろは？',
      qEn: 'Which colours does Mondrian most often use?',
      choices: [{ jp: 'あか・あお・き・くろ・しろ', en: 'red, blue, yellow, black, white' }, { jp: 'みどり・むらさき・オレンジ', en: 'green, purple, orange' }, { jp: 'ピンク・ベージュ・はいいろ', en: 'pink, beige, grey' }],
      correctJp: 'あか・あお・き・くろ・しろ',
    },
    {
      visual: '🌷💧',
      q: 'Monet が えがいた ゆうめいな えは？',
      qEn: 'What is Monet\'s most famous subject to paint?',
      choices: [{ jp: 'すいれんの いけ', en: 'water lilies pond' }, { jp: 'まちの けしき', en: 'city streets' }, { jp: 'きかがくてきな かたち', en: 'geometric shapes' }],
      correctJp: 'すいれんの いけ',
    },
    {
      visual: '🔴⚫🔴⚫',
      q: 'Yayoi Kusama は どこの くにの アーティスト？',
      qEn: 'Which country is Yayoi Kusama from?',
      choices: [{ jp: 'にほん', en: 'Japan' }, { jp: 'フランス', en: 'France' }, { jp: 'オランダ', en: 'Netherlands' }],
      correctJp: 'にほん',
    },
    {
      visual: '🍂🪨',
      q: 'Andy Goldsworthy の アートは どこで みられる？',
      qEn: 'Where can you usually see Andy Goldsworthy\'s art?',
      choices: [{ jp: 'しぜんの なか（そと）', en: 'in nature (outdoors)' }, { jp: 'びじゅつかん の なか', en: 'inside a gallery' }, { jp: 'えはがき の うえ', en: 'on postcards' }],
      correctJp: 'しぜんの なか（そと）',
    },
    {
      visual: '🎨',
      q: 'えを かくことを なんと いう？',
      qEn: 'What do we call making pictures with paint or pencil?',
      choices: [{ jp: 'えをかく（drawing/painting）', en: 'drawing or painting' }, { jp: 'ちょうこく', en: 'sculpture' }, { jp: 'コラージュ', en: 'collage' }],
      correctJp: 'えをかく（drawing/painting）',
    },
    {
      visual: '🏺',
      q: 'ねんどや いしで たいりつした さくひんを なんと いう？',
      qEn: 'A three-dimensional artwork made from clay or stone is called...?',
      choices: [{ jp: 'ちょうこく', en: 'sculpture' }, { jp: 'えをかく', en: 'drawing' }, { jp: 'コラージュ', en: 'collage' }],
      correctJp: 'ちょうこく',
    },
    {
      visual: '✂️📰',
      q: 'きりぬきを はって さくひんを つくることを なんと いう？',
      qEn: 'Sticking cut pieces together to make artwork is called...?',
      choices: [{ jp: 'コラージュ', en: 'collage' }, { jp: 'ちょうこく', en: 'sculpture' }, { jp: 'えをかく', en: 'drawing' }],
      correctJp: 'コラージュ',
    },
  ],
  pool2: [
    {
      visual: '🖼️',
      q: 'Mondrian の えの とくちょうは？',
      qEn: 'What is special about Mondrian\'s painting style?',
      choices: [{ jp: 'まっすぐな せんと げんしょくの ます', en: 'straight lines and blocks of primary colour' }, { jp: 'やわらかな ぼかしで しぜんを えがく', en: 'soft blurred natural scenes' }, { jp: 'てんてんで いっぱい', en: 'covered in dots' }],
      correctJp: 'まっすぐな せんと げんしょくの ます',
    },
    {
      visual: '🌸',
      q: 'Monet の えのスタイルを なんと いう？',
      qEn: 'What art style is Monet associated with?',
      choices: [{ jp: 'Impressionism（いんしょうは）', en: 'Impressionism' }, { jp: 'Abstract（ちゅうしょうが）', en: 'Abstract art' }, { jp: 'Pop Art', en: 'Pop Art' }],
      correctJp: 'Impressionism（いんしょうは）',
    },
    {
      visual: '🔴⚪🔴⚪',
      q: 'Yayoi Kusama の てんてんの もようは なにを つたえる？',
      qEn: 'What feeling do Kusama\'s dots create?',
      choices: [{ jp: 'むげんに つづく かんじ', en: 'a feeling of endless infinity' }, { jp: 'かなしみ', en: 'sadness' }, { jp: 'かんたんな かたち', en: 'simple shapes' }],
      correctJp: 'むげんに つづく かんじ',
    },
    {
      visual: '🍂',
      q: 'Andy Goldsworthy が つかう そざいは？',
      qEn: 'What materials does Andy Goldsworthy use?',
      choices: [{ jp: 'は・いし・こおりなど しぜんのもの', en: 'leaves, stones, ice and other natural things' }, { jp: 'プラスチックや てつ', en: 'plastic and metal' }, { jp: 'えのぐと キャンバス', en: 'paint and canvas' }],
      correctJp: 'は・いし・こおりなど しぜんのもの',
    },
    {
      visual: '🌀',
      q: 'アボリジナルの アートで てんてんは なにを あらわす？',
      qEn: 'In Aboriginal art, what do the dots represent?',
      choices: [{ jp: 'ものがたりや せいち', en: 'stories and sacred places' }, { jp: 'なにも あらわさない', en: 'nothing in particular' }, { jp: 'ただの かざり', en: 'just decoration' }],
      correctJp: 'ものがたりや せいち',
    },
    {
      visual: '🎨',
      q: 'アーティストが えを かくときに つかう もりょうを なんと いう？',
      qEn: 'What do we call the flat surface an artist paints on?',
      choices: [{ jp: 'キャンバス', en: 'canvas' }, { jp: 'パレット', en: 'palette' }, { jp: 'ブラシ', en: 'brush' }],
      correctJp: 'キャンバス',
    },
    {
      visual: '🟥🟦🟨',
      q: 'Mondrian は どこの くにの アーティスト？',
      qEn: 'Which country was Mondrian from?',
      choices: [{ jp: 'オランダ', en: 'Netherlands' }, { jp: 'フランス', en: 'France' }, { jp: 'にほん', en: 'Japan' }],
      correctJp: 'オランダ',
    },
    {
      visual: '🌷',
      q: 'Monet は どこの くにの アーティスト？',
      qEn: 'Which country was Monet from?',
      choices: [{ jp: 'フランス', en: 'France' }, { jp: 'イギリス', en: 'Britain' }, { jp: 'オランダ', en: 'Netherlands' }],
      correctJp: 'フランス',
    },
    {
      visual: '✂️📰',
      q: 'コラージュで つかう ものは？',
      qEn: 'What do you need to make a collage?',
      choices: [{ jp: 'はさみ・のり・かみや ぬの', en: 'scissors, glue, paper or fabric' }, { jp: 'ねんどと てみず', en: 'clay and water' }, { jp: 'えのぐと ブラシ だけ', en: 'only paint and brushes' }],
      correctJp: 'はさみ・のり・かみや ぬの',
    },
    {
      visual: '🖼️',
      q: 'びじゅつかんで アートを みて、どんな ことを かんがえる？',
      qEn: 'When looking at art in a gallery, what is it good to think about?',
      choices: [{ jp: 'なにを かんじるか、なにが みえるか', en: 'what you feel and what you see' }, { jp: 'はやく でたい', en: 'how to leave quickly' }, { jp: 'おなじ えを かけるか', en: 'whether you can copy it exactly' }],
      correctJp: 'なにを かんじるか、なにが みえるか',
    },
    {
      visual: '🎨',
      q: 'アートの ぎじゅつに ふくまれる ものは？',
      qEn: 'Which of these is an art technique?',
      choices: [{ jp: 'プリント（はんが）', en: 'printmaking' }, { jp: 'およぐ', en: 'swimming' }, { jp: 'もじを よむ', en: 'reading text' }],
      correctJp: 'プリント（はんが）',
    },
    {
      visual: '🌟',
      q: 'アートを べんきょうする りゆうは？',
      qEn: 'Why do we study art?',
      choices: [{ jp: 'そうぞうりょくを のばし じぶんを あらわすため', en: 'to develop creativity and express ourselves' }, { jp: 'えを うるため', en: 'to sell paintings' }, { jp: 'むずかしいから', en: 'because it is difficult' }],
      correctJp: 'そうぞうりょくを のばし じぶんを あらわすため',
    },
  ],
}

// ─── World 4 module registry ──────────────────────────────────────────────────

export const WORLD4_MODULES = [
  { id: 1, titleJp: 'いろをまぜよう',         titleEn: 'Colours & Mixing', emoji: '🎨', color: '#E8963E', data: m41 },
  { id: 2, titleJp: 'もようをみつけよう',     titleEn: 'Patterns in Art',  emoji: '🔶', color: '#D45B5B', data: m42 },
  { id: 3, titleJp: 'ゆうめいなアートをしろう', titleEn: 'Famous Art',     emoji: '🖼️', color: '#4DAAAA', data: m43 },
]
