import { shuffle, buildSession } from './questionData.js'
export { shuffle, buildSession }

// ─── World 2 Module 1 — Continents and Oceans (たいりくとうみ) ─────────────────

export const m21 = {
  pool1: [
    {
      visual: '🌍',
      q: 'たいりくは いくつ ある？',
      qEn: 'How many continents are there?',
      choices: [{ jp: 'ななつ', en: '7' }, { jp: 'いつつ', en: '5' }, { jp: 'むっつ', en: '6' }],
      correctJp: 'ななつ',
    },
    {
      visual: '🗺️',
      q: 'いちばん おおきい たいりくは？',
      qEn: 'Which is the largest continent?',
      choices: [{ jp: 'あじあ', en: 'Asia' }, { jp: 'あふりか', en: 'Africa' }, { jp: 'よーろっぱ', en: 'Europe' }],
      correctJp: 'あじあ',
    },
    {
      visual: '🇯🇵',
      q: 'にほんは どの たいりくに ある？',
      qEn: 'Japan is in which continent?',
      choices: [{ jp: 'あじあ', en: 'Asia' }, { jp: 'よーろっぱ', en: 'Europe' }, { jp: 'おせあにあ', en: 'Oceania' }],
      correctJp: 'あじあ',
    },
    {
      visual: '🇬🇧',
      q: 'イギリスは どの たいりくに ある？',
      qEn: 'The UK is in which continent?',
      choices: [{ jp: 'よーろっぱ', en: 'Europe' }, { jp: 'あじあ', en: 'Asia' }, { jp: 'あふりか', en: 'Africa' }],
      correctJp: 'よーろっぱ',
    },
    {
      visual: '🧊',
      q: 'みなみきょくに ある たいりくは？',
      qEn: 'Which continent is at the South Pole?',
      choices: [{ jp: 'なんきょく', en: 'Antarctica' }, { jp: 'あふりか', en: 'Africa' }, { jp: 'おせあにあ', en: 'Oceania' }],
      correctJp: 'なんきょく',
    },
    {
      visual: '🌿',
      q: 'アマゾンの もりが ある たいりくは？',
      qEn: 'The Amazon rainforest is in which continent?',
      choices: [{ jp: 'みなみあめりか', en: 'South America' }, { jp: 'あふりか', en: 'Africa' }, { jp: 'きたあめりか', en: 'North America' }],
      correctJp: 'みなみあめりか',
    },
    {
      visual: '🏜️',
      q: 'サハラさばくが ある たいりくは？',
      qEn: 'The Sahara Desert is in which continent?',
      choices: [{ jp: 'あふりか', en: 'Africa' }, { jp: 'あじあ', en: 'Asia' }, { jp: 'みなみあめりか', en: 'South America' }],
      correctJp: 'あふりか',
    },
    {
      visual: '🇦🇪',
      q: 'ドバイは どの たいりくに ある？',
      qEn: 'Dubai is in which continent?',
      choices: [{ jp: 'あじあ', en: 'Asia' }, { jp: 'よーろっぱ', en: 'Europe' }, { jp: 'あふりか', en: 'Africa' }],
      correctJp: 'あじあ',
    },
    {
      visual: '🦘',
      q: 'カンガルーが すむ たいりくは？',
      qEn: 'Kangaroos live in which continent?',
      choices: [{ jp: 'おせあにあ', en: 'Oceania' }, { jp: 'あじあ', en: 'Asia' }, { jp: 'みなみあめりか', en: 'South America' }],
      correctJp: 'おせあにあ',
    },
    {
      visual: '🇧🇷',
      q: 'ブラジルが ある たいりくは？',
      qEn: 'Brazil is in which continent?',
      choices: [{ jp: 'みなみあめりか', en: 'South America' }, { jp: 'きたあめりか', en: 'North America' }, { jp: 'あふりか', en: 'Africa' }],
      correctJp: 'みなみあめりか',
    },
    {
      visual: '🇪🇸',
      q: 'スペインは どの たいりくに ある？',
      qEn: 'Spain is in which continent?',
      choices: [{ jp: 'よーろっぱ', en: 'Europe' }, { jp: 'あじあ', en: 'Asia' }, { jp: 'あふりか', en: 'Africa' }],
      correctJp: 'よーろっぱ',
    },
    {
      visual: '🗽',
      q: 'アメリカは どの たいりくに ある？',
      qEn: 'The USA is in which continent?',
      choices: [{ jp: 'きたあめりか', en: 'North America' }, { jp: 'みなみあめりか', en: 'South America' }, { jp: 'よーろっぱ', en: 'Europe' }],
      correctJp: 'きたあめりか',
    },
  ],
  pool2: [
    {
      visual: '🌊',
      q: 'たいようは いくつ ある？',
      qEn: 'How many oceans are there?',
      choices: [{ jp: 'いつつ', en: '5' }, { jp: 'ななつ', en: '7' }, { jp: 'みっつ', en: '3' }],
      correctJp: 'いつつ',
    },
    {
      visual: '🌏',
      q: 'いちばん おおきい たいようは？',
      qEn: 'Which is the largest ocean?',
      choices: [{ jp: 'たいへいよう', en: 'Pacific Ocean' }, { jp: 'たいせいよう', en: 'Atlantic Ocean' }, { jp: 'いんどよう', en: 'Indian Ocean' }],
      correctJp: 'たいへいよう',
    },
    {
      visual: '🚢',
      q: 'よーろっぱと アメリカの あいだの うみは？',
      qEn: 'Which ocean is between Europe and America?',
      choices: [{ jp: 'たいせいよう', en: 'Atlantic Ocean' }, { jp: 'たいへいよう', en: 'Pacific Ocean' }, { jp: 'いんどよう', en: 'Indian Ocean' }],
      correctJp: 'たいせいよう',
    },
    {
      visual: '🧊',
      q: 'なんきょくを とりまく うみは？',
      qEn: 'Which ocean surrounds Antarctica?',
      choices: [{ jp: 'なんきょくかい', en: 'Southern Ocean' }, { jp: 'ほっきょくかい', en: 'Arctic Ocean' }, { jp: 'いんどよう', en: 'Indian Ocean' }],
      correctJp: 'なんきょくかい',
    },
    {
      visual: '🐋',
      q: 'インドの よこに ある うみは？',
      qEn: 'Which ocean is beside India?',
      choices: [{ jp: 'いんどよう', en: 'Indian Ocean' }, { jp: 'たいへいよう', en: 'Pacific Ocean' }, { jp: 'たいせいよう', en: 'Atlantic Ocean' }],
      correctJp: 'いんどよう',
    },
    {
      visual: '🐻‍❄️',
      q: 'ほっきょくかいは どこに ある？',
      qEn: 'Where is the Arctic Ocean?',
      choices: [{ jp: 'きたきょく', en: 'North Pole' }, { jp: 'みなみきょく', en: 'South Pole' }, { jp: 'せきどうちかく', en: 'near the Equator' }],
      correctJp: 'きたきょく',
    },
    {
      visual: '🌍',
      q: 'くには ない たいりくは どれ？',
      qEn: 'Which continent has no countries?',
      choices: [{ jp: 'なんきょく', en: 'Antarctica' }, { jp: 'あふりか', en: 'Africa' }, { jp: 'おせあにあ', en: 'Oceania' }],
      correctJp: 'なんきょく',
    },
    {
      visual: '☀️',
      q: 'せきどうちかくは どんな てんき？',
      qEn: 'What is the weather like near the Equator?',
      choices: [{ jp: 'あつい', en: 'hot' }, { jp: 'さむい', en: 'cold' }, { jp: 'すずしい', en: 'cool' }],
      correctJp: 'あつい',
    },
    {
      visual: '🌊',
      q: 'たいへいようと たいせいようで おおきいのは？',
      qEn: 'Which is bigger, Pacific or Atlantic?',
      choices: [{ jp: 'たいへいよう', en: 'Pacific Ocean' }, { jp: 'たいせいよう', en: 'Atlantic Ocean' }, { jp: 'おなじ おおきさ', en: 'the same size' }],
      correctJp: 'たいへいよう',
    },
    {
      visual: '🗺️',
      q: 'たいりくと たいようを あわせると いくつ？',
      qEn: 'Continents and oceans together make how many?',
      choices: [{ jp: 'じゅうに', en: '12' }, { jp: 'じゅう', en: '10' }, { jp: 'じゅうご', en: '15' }],
      correctJp: 'じゅうに',
    },
    {
      visual: '🌏',
      q: 'アジアと アメリカの あいだの うみは？',
      qEn: 'Which ocean lies between Asia and America?',
      choices: [{ jp: 'たいへいよう', en: 'Pacific Ocean' }, { jp: 'たいせいよう', en: 'Atlantic Ocean' }, { jp: 'いんどよう', en: 'Indian Ocean' }],
      correctJp: 'たいへいよう',
    },
    {
      visual: '🇬🇧',
      q: 'イギリスの にしの たいようは？',
      qEn: 'Which ocean is to the west of the UK?',
      choices: [{ jp: 'たいせいよう', en: 'Atlantic Ocean' }, { jp: 'たいへいよう', en: 'Pacific Ocean' }, { jp: 'いんどよう', en: 'Indian Ocean' }],
      correctJp: 'たいせいよう',
    },
  ],
}

// ─── World 2 Module 2 — The United Kingdom (イギリス) ─────────────────────────

export const m22 = {
  pool1: [
    {
      visual: '🇬🇧',
      q: 'イギリスは いくつの くにから できている？',
      qEn: 'How many countries make up the UK?',
      choices: [{ jp: 'よっつ', en: '4' }, { jp: 'みっつ', en: '3' }, { jp: 'いつつ', en: '5' }],
      correctJp: 'よっつ',
    },
    {
      visual: '🏙️',
      q: 'イングランドの しゅとは？',
      qEn: 'What is the capital of England?',
      choices: [{ jp: 'ろんどん', en: 'London' }, { jp: 'えでぃんばら', en: 'Edinburgh' }, { jp: 'かーでぃふ', en: 'Cardiff' }],
      correctJp: 'ろんどん',
    },
    {
      visual: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
      q: 'スコットランドは イギリスの どちらに ある？',
      qEn: 'Where is Scotland in the UK?',
      choices: [{ jp: 'きた', en: 'north' }, { jp: 'みなみ', en: 'south' }, { jp: 'にし', en: 'west' }],
      correctJp: 'きた',
    },
    {
      visual: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
      q: 'ウェールズは イングランドの どちらに ある？',
      qEn: 'Wales is to which side of England?',
      choices: [{ jp: 'にし', en: 'west' }, { jp: 'ひがし', en: 'east' }, { jp: 'きた', en: 'north' }],
      correctJp: 'にし',
    },
    {
      visual: '🐉',
      q: 'あかいりゅうの はたを もつ くには？',
      qEn: 'Which country has a red dragon on its flag?',
      choices: [{ jp: 'うぇーるず', en: 'Wales' }, { jp: 'すこっとらんど', en: 'Scotland' }, { jp: 'いんぐらんど', en: 'England' }],
      correctJp: 'うぇーるず',
    },
    {
      visual: '🏰',
      q: 'スコットランドの しゅとは？',
      qEn: 'What is the capital of Scotland?',
      choices: [{ jp: 'えでぃんばら', en: 'Edinburgh' }, { jp: 'ろんどん', en: 'London' }, { jp: 'べるふぁすと', en: 'Belfast' }],
      correctJp: 'えでぃんばら',
    },
    {
      visual: '🇬🇧',
      q: 'いんぐらんど、すこっとらんど、うぇーるず、あと ひとつは？',
      qEn: 'England, Scotland, Wales and...?',
      choices: [{ jp: 'きたあいるらんど', en: 'Northern Ireland' }, { jp: 'あいるらんど', en: 'Ireland' }, { jp: 'ふらんす', en: 'France' }],
      correctJp: 'きたあいるらんど',
    },
    {
      visual: '👑',
      q: 'イギリスで いちばん おおきい くには？',
      qEn: 'Which is the largest country in the UK?',
      choices: [{ jp: 'いんぐらんど', en: 'England' }, { jp: 'すこっとらんど', en: 'Scotland' }, { jp: 'うぇーるず', en: 'Wales' }],
      correctJp: 'いんぐらんど',
    },
    {
      visual: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
      q: 'ウェールズの しゅとは？',
      qEn: 'What is the capital of Wales?',
      choices: [{ jp: 'かーでぃふ', en: 'Cardiff' }, { jp: 'ろんどん', en: 'London' }, { jp: 'えでぃんばら', en: 'Edinburgh' }],
      correctJp: 'かーでぃふ',
    },
    {
      visual: '🍀',
      q: 'きたアイルランドの しゅとは？',
      qEn: 'What is the capital of Northern Ireland?',
      choices: [{ jp: 'べるふぁすと', en: 'Belfast' }, { jp: 'かーでぃふ', en: 'Cardiff' }, { jp: 'えでぃんばら', en: 'Edinburgh' }],
      correctJp: 'べるふぁすと',
    },
    {
      visual: '🌊',
      q: 'イギリスの まわりには なにが ある？',
      qEn: 'What surrounds the UK?',
      choices: [{ jp: 'うみ', en: 'sea' }, { jp: 'やま', en: 'mountains' }, { jp: 'さばく', en: 'desert' }],
      correctJp: 'うみ',
    },
    {
      visual: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
      q: 'スコットランドは イングランドの どちらに ある？',
      qEn: 'Scotland is to which side of England?',
      choices: [{ jp: 'きた', en: 'north' }, { jp: 'みなみ', en: 'south' }, { jp: 'ひがし', en: 'east' }],
      correctJp: 'きた',
    },
  ],
  pool2: [
    {
      visual: '🍀',
      q: 'ベルファストは どの くにの しゅとか？',
      qEn: 'Belfast is the capital of which country?',
      choices: [{ jp: 'きたあいるらんど', en: 'Northern Ireland' }, { jp: 'うぇーるず', en: 'Wales' }, { jp: 'すこっとらんど', en: 'Scotland' }],
      correctJp: 'きたあいるらんど',
    },
    {
      visual: '🐉',
      q: 'カーディフは どの くにの しゅとか？',
      qEn: 'Cardiff is the capital of which country?',
      choices: [{ jp: 'うぇーるず', en: 'Wales' }, { jp: 'いんぐらんど', en: 'England' }, { jp: 'きたあいるらんど', en: 'Northern Ireland' }],
      correctJp: 'うぇーるず',
    },
    {
      visual: '🏰',
      q: 'エディンバラは どの くにの しゅとか？',
      qEn: 'Edinburgh is the capital of which country?',
      choices: [{ jp: 'すこっとらんど', en: 'Scotland' }, { jp: 'いんぐらんど', en: 'England' }, { jp: 'うぇーるず', en: 'Wales' }],
      correctJp: 'すこっとらんど',
    },
    {
      visual: '👑',
      q: 'ロンドンは どの くにの しゅとか？',
      qEn: 'London is the capital of which country?',
      choices: [{ jp: 'いんぐらんど', en: 'England' }, { jp: 'すこっとらんど', en: 'Scotland' }, { jp: 'きたあいるらんど', en: 'Northern Ireland' }],
      correctJp: 'いんぐらんど',
    },
    {
      visual: '🚢',
      q: 'イングランドと フランスの あいだの うみは？',
      qEn: 'What sea lies between England and France?',
      choices: [{ jp: 'えいきょくかいきょう', en: 'English Channel' }, { jp: 'あいりっしゅかい', en: 'Irish Sea' }, { jp: 'きたかい', en: 'North Sea' }],
      correctJp: 'えいきょくかいきょう',
    },
    {
      visual: '🌊',
      q: 'イギリスの にしに ある うみは？',
      qEn: 'Which sea is to the west of the UK?',
      choices: [{ jp: 'あいりっしゅかい', en: 'Irish Sea' }, { jp: 'きたかい', en: 'North Sea' }, { jp: 'えいきょくかいきょう', en: 'English Channel' }],
      correctJp: 'あいりっしゅかい',
    },
    {
      visual: '🌊',
      q: 'きたかいは イギリスの どちらに ある？',
      qEn: 'The North Sea is to which side of the UK?',
      choices: [{ jp: 'ひがし', en: 'east' }, { jp: 'にし', en: 'west' }, { jp: 'みなみ', en: 'south' }],
      correctJp: 'ひがし',
    },
    {
      visual: '🏙️',
      q: 'ロンドンと エディンバラで きたに あるのは？',
      qEn: 'Which is further north, London or Edinburgh?',
      choices: [{ jp: 'えでぃんばら', en: 'Edinburgh' }, { jp: 'ろんどん', en: 'London' }, { jp: 'おなじ', en: 'the same' }],
      correctJp: 'えでぃんばら',
    },
    {
      visual: '🌊',
      q: 'テムズがわが ながれる まちは？',
      qEn: 'The River Thames flows through which city?',
      choices: [{ jp: 'ろんどん', en: 'London' }, { jp: 'えでぃんばら', en: 'Edinburgh' }, { jp: 'かーでぃふ', en: 'Cardiff' }],
      correctJp: 'ろんどん',
    },
    {
      visual: '🇬🇧',
      q: 'イギリスの にしの おおきな うみは？',
      qEn: 'Which large ocean is to the west of the UK?',
      choices: [{ jp: 'たいせいよう', en: 'Atlantic Ocean' }, { jp: 'たいへいよう', en: 'Pacific Ocean' }, { jp: 'いんどよう', en: 'Indian Ocean' }],
      correctJp: 'たいせいよう',
    },
    {
      visual: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
      q: 'ウェールズの りゅうは どんな いろ？',
      qEn: 'What colour is the dragon on the Welsh flag?',
      choices: [{ jp: 'あかい', en: 'red' }, { jp: 'あおい', en: 'blue' }, { jp: 'みどり', en: 'green' }],
      correctJp: 'あかい',
    },
    {
      visual: '🗺️',
      q: 'イギリスの しゅとを すべて いえる？ ろんどん、えでぃんばら、かーでぃふ、あとひとつは？',
      qEn: 'London, Edinburgh, Cardiff and...?',
      choices: [{ jp: 'べるふぁすと', en: 'Belfast' }, { jp: 'おっくすふぉど', en: 'Oxford' }, { jp: 'りばぷーる', en: 'Liverpool' }],
      correctJp: 'べるふぁすと',
    },
  ],
}

// ─── World 2 Module 3 — Weather (てんき) ──────────────────────────────────────

export const m23 = {
  pool1: [
    {
      visual: '☀️',
      q: 'この マークは どんな てんき？',
      qEn: 'What weather does this symbol show?',
      choices: [{ jp: 'はれ', en: 'sunny' }, { jp: 'あめ', en: 'rainy' }, { jp: 'くもり', en: 'cloudy' }],
      correctJp: 'はれ',
    },
    {
      visual: '🌧️',
      q: 'この マークは どんな てんき？',
      qEn: 'What weather does this symbol show?',
      choices: [{ jp: 'あめ', en: 'rainy' }, { jp: 'ゆき', en: 'snowy' }, { jp: 'はれ', en: 'sunny' }],
      correctJp: 'あめ',
    },
    {
      visual: '❄️',
      q: 'しろくて つめたい てんきは？',
      qEn: 'What is the white, cold type of weather called?',
      choices: [{ jp: 'ゆき', en: 'snow' }, { jp: 'あめ', en: 'rain' }, { jp: 'かぜ', en: 'wind' }],
      correctJp: 'ゆき',
    },
    {
      visual: '💨',
      q: 'きが ゆれる てんきは？',
      qEn: 'What weather makes trees bend?',
      choices: [{ jp: 'かぜ', en: 'windy' }, { jp: 'あめ', en: 'rainy' }, { jp: 'はれ', en: 'sunny' }],
      correctJp: 'かぜ',
    },
    {
      visual: '⛈️',
      q: 'かみなりと あめの てんきは？',
      qEn: 'What is the weather with thunder and rain called?',
      choices: [{ jp: 'あらし', en: 'stormy' }, { jp: 'くもり', en: 'cloudy' }, { jp: 'ゆき', en: 'snowy' }],
      correctJp: 'あらし',
    },
    {
      visual: '☁️',
      q: 'この マークは どんな てんき？',
      qEn: 'What weather does this symbol show?',
      choices: [{ jp: 'くもり', en: 'cloudy' }, { jp: 'はれ', en: 'sunny' }, { jp: 'あめ', en: 'rainy' }],
      correctJp: 'くもり',
    },
    {
      visual: '☀️🌧️',
      q: 'はれているのに あめが ふっている。なにが でるかも？',
      qEn: 'Sun and rain together might make a...?',
      choices: [{ jp: 'にじ', en: 'rainbow' }, { jp: 'ゆき', en: 'snow' }, { jp: 'あらし', en: 'storm' }],
      correctJp: 'にじ',
    },
    {
      visual: '🌡️',
      q: 'おんどを はかる どうぐは？',
      qEn: 'What tool measures temperature?',
      choices: [{ jp: 'おんどけい', en: 'thermometer' }, { jp: 'じしゃく', en: 'compass' }, { jp: 'めがね', en: 'magnifying glass' }],
      correctJp: 'おんどけい',
    },
    {
      visual: '❄️',
      q: 'ゆきが ふる きせつは？',
      qEn: 'In which season does snow usually fall?',
      choices: [{ jp: 'ふゆ', en: 'winter' }, { jp: 'なつ', en: 'summer' }, { jp: 'はる', en: 'spring' }],
      correctJp: 'ふゆ',
    },
    {
      visual: '☀️',
      q: 'イギリスで いちばん あたたかい きせつは？',
      qEn: 'Which season is warmest in the UK?',
      choices: [{ jp: 'なつ', en: 'summer' }, { jp: 'ふゆ', en: 'winter' }, { jp: 'あき', en: 'autumn' }],
      correctJp: 'なつ',
    },
    {
      visual: '🌈',
      q: 'にじは いくつの いろが ある？',
      qEn: 'How many colours are in a rainbow?',
      choices: [{ jp: 'ななつ', en: '7' }, { jp: 'いつつ', en: '5' }, { jp: 'みっつ', en: '3' }],
      correctJp: 'ななつ',
    },
    {
      visual: '🌬️',
      q: 'てんきで ないのは どれ？',
      qEn: 'Which of these is NOT a type of weather?',
      choices: [{ jp: 'やま', en: 'mountain' }, { jp: 'はれ', en: 'sunny' }, { jp: 'あめ', en: 'rainy' }],
      correctJp: 'やま',
    },
  ],
  pool2: [
    {
      visual: '🌍',
      q: 'ちきゅうで いちばん あつい ばしょは？',
      qEn: 'Where is the hottest place on Earth?',
      choices: [{ jp: 'せきどうちかく', en: 'near the Equator' }, { jp: 'きたきょく', en: 'North Pole' }, { jp: 'みなみきょく', en: 'South Pole' }],
      correctJp: 'せきどうちかく',
    },
    {
      visual: '🧊',
      q: 'ちきゅうで いちばん さむい ばしょは？',
      qEn: 'Where is the coldest place on Earth?',
      choices: [{ jp: 'きょくちほう', en: 'the poles' }, { jp: 'せきどうちかく', en: 'near the Equator' }, { jp: 'うみの なか', en: 'in the ocean' }],
      correctJp: 'きょくちほう',
    },
    {
      visual: '🌐',
      q: 'せきどうとは なに？',
      qEn: 'What is the Equator?',
      choices: [{ jp: 'ちきゅうの まんなかの せん', en: 'an imaginary line around Earth\'s middle' }, { jp: 'やまの てっぺん', en: 'the top of a mountain' }, { jp: 'うみの そこ', en: 'the bottom of the ocean' }],
      correctJp: 'ちきゅうの まんなかの せん',
    },
    {
      visual: '🇦🇪',
      q: 'ドバイが あつい りゆうは？',
      qEn: 'Why is Dubai so hot?',
      choices: [{ jp: 'せきどうに ちかい', en: 'it is near the Equator' }, { jp: 'きょくに ちかい', en: 'it is near a pole' }, { jp: 'うみの なかに ある', en: 'it is in the ocean' }],
      correctJp: 'せきどうに ちかい',
    },
    {
      visual: '🐧',
      q: 'なんきょくは どんな ところ？',
      qEn: 'What is Antarctica like?',
      choices: [{ jp: 'とても さむい', en: 'very cold' }, { jp: 'とても あつい', en: 'very hot' }, { jp: 'おだやか', en: 'mild' }],
      correctJp: 'とても さむい',
    },
    {
      visual: '🌍',
      q: 'せきどうから とおい ほど てんきは？',
      qEn: 'The further from the Equator, the weather gets...?',
      choices: [{ jp: 'すずしく なる', en: 'cooler' }, { jp: 'あつく なる', en: 'hotter' }, { jp: 'あめが おおくなる', en: 'rainier' }],
      correctJp: 'すずしく なる',
    },
    {
      visual: '🌡️',
      q: 'きたきょくと ドバイで さむいのは？',
      qEn: 'Which is colder, the North Pole or Dubai?',
      choices: [{ jp: 'きたきょく', en: 'North Pole' }, { jp: 'ドバイ', en: 'Dubai' }, { jp: 'おなじ', en: 'the same' }],
      correctJp: 'きたきょく',
    },
    {
      visual: '☀️',
      q: 'せきどうちかくの くには？',
      qEn: 'Countries near the Equator are usually...?',
      choices: [{ jp: 'あつい', en: 'hot' }, { jp: 'さむい', en: 'cold' }, { jp: 'ゆき が おおい', en: 'snowy' }],
      correctJp: 'あつい',
    },
    {
      visual: '🇬🇧',
      q: 'イギリスの てんきは いちねんじゅう おなじ？',
      qEn: 'Is the UK weather the same all year?',
      choices: [{ jp: 'いいえ、きせつで かわる', en: 'no, it changes with seasons' }, { jp: 'はい、つねに あつい', en: 'yes, always hot' }, { jp: 'はい、つねに さむい', en: 'yes, always cold' }],
      correctJp: 'いいえ、きせつで かわる',
    },
    {
      visual: '🌦️',
      q: 'まいとし おなじ きせつが くることを なんと いう？',
      qEn: 'Weather that follows the same pattern each year is called...?',
      choices: [{ jp: 'きせつの てんき', en: 'seasonal weather' }, { jp: 'とつぜんの あめ', en: 'sudden rain' }, { jp: 'たいふう', en: 'typhoon' }],
      correctJp: 'きせつの てんき',
    },
    {
      visual: '🌍',
      q: 'きたきょくは みなみきょくより あたたかい？',
      qEn: 'Is the North Pole slightly warmer than the South Pole?',
      choices: [{ jp: 'はい', en: 'yes' }, { jp: 'いいえ', en: 'no' }, { jp: 'おなじ', en: 'the same' }],
      correctJp: 'はい',
    },
    {
      visual: '🌧️',
      q: 'イギリスは あめが おおい。なぜ？',
      qEn: 'The UK gets a lot of rain. Why?',
      choices: [{ jp: 'たいせいようから しめった かぜが くる', en: 'moist winds come from the Atlantic' }, { jp: 'せきどうに ちかい', en: 'it is near the Equator' }, { jp: 'きたきょくに ちかい', en: 'it is near the North Pole' }],
      correctJp: 'たいせいようから しめった かぜが くる',
    },
  ],
}

// ─── World 2 Module 4 — Physical and Human Features (ちけいとまち) ─────────────

export const m24 = {
  pool1: [
    {
      visual: '🏔️',
      q: 'これは しぜんの ちりてきな とくちょう。なんと いう？',
      qEn: 'This tall natural landform is called a...?',
      choices: [{ jp: 'やま', en: 'mountain' }, { jp: 'おか', en: 'hill' }, { jp: 'たに', en: 'valley' }],
      correctJp: 'やま',
    },
    {
      visual: '🌊',
      q: 'おおきな みずの たいまつは？',
      qEn: 'A very large area of salt water is called a...?',
      choices: [{ jp: 'うみ', en: 'sea / ocean' }, { jp: 'かわ', en: 'river' }, { jp: 'みずうみ', en: 'lake' }],
      correctJp: 'うみ',
    },
    {
      visual: '🌲🌲🌲',
      q: 'たくさんの きが あつまった ところは？',
      qEn: 'A large area of trees is called a...?',
      choices: [{ jp: 'もり', en: 'forest' }, { jp: 'のはら', en: 'meadow' }, { jp: 'やま', en: 'mountain' }],
      correctJp: 'もり',
    },
    {
      visual: '🏖️',
      q: 'うみぎわの すなの ところは？',
      qEn: 'The sandy area at the edge of the sea is a...?',
      choices: [{ jp: 'かいがん', en: 'beach' }, { jp: 'がけ', en: 'cliff' }, { jp: 'みなと', en: 'port' }],
      correctJp: 'かいがん',
    },
    {
      visual: '🪨',
      q: 'うみの そばの たかい いわの へりを なんと いう？',
      qEn: 'The high rocky edge beside the sea is a...?',
      choices: [{ jp: 'がけ', en: 'cliff' }, { jp: 'かいがん', en: 'beach' }, { jp: 'おか', en: 'hill' }],
      correctJp: 'がけ',
    },
    {
      visual: '🏞️',
      q: 'やまと やまの あいだの ひくい ところは？',
      qEn: 'The low land between hills is a...?',
      choices: [{ jp: 'たに', en: 'valley' }, { jp: 'やま', en: 'mountain' }, { jp: 'かいがん', en: 'beach' }],
      correctJp: 'たに',
    },
    {
      visual: '🌊',
      q: 'かわとは なに？',
      qEn: 'What is a river?',
      choices: [{ jp: 'みずが ながれる ながい みち', en: 'water flowing through land' }, { jp: 'うみの なかの しま', en: 'an island in the sea' }, { jp: 'さかなが すむ うみ', en: 'the sea where fish live' }],
      correctJp: 'みずが ながれる ながい みち',
    },
    {
      visual: '🗺️',
      q: 'りくと うみが であう ところを なんと いう？',
      qEn: 'Where land meets the sea is called the...?',
      choices: [{ jp: 'かいがん / コースト', en: 'coast' }, { jp: 'たに', en: 'valley' }, { jp: 'もり', en: 'forest' }],
      correctJp: 'かいがん / コースト',
    },
    {
      visual: '⛰️',
      q: 'おかと やまで おおきいのは？',
      qEn: 'Which is bigger, a hill or a mountain?',
      choices: [{ jp: 'やま', en: 'mountain' }, { jp: 'おか', en: 'hill' }, { jp: 'おなじ おおきさ', en: 'the same' }],
      correctJp: 'やま',
    },
    {
      visual: '🌊',
      q: 'かわは どこへ ながれる？',
      qEn: 'Where does a river flow to?',
      choices: [{ jp: 'うみへ', en: 'to the sea' }, { jp: 'やまへ', en: 'to the mountain' }, { jp: 'そらへ', en: 'to the sky' }],
      correctJp: 'うみへ',
    },
    {
      visual: '🏔️',
      q: 'やまは しぜんの もの？',
      qEn: 'Is a mountain a natural feature?',
      choices: [{ jp: 'はい、しぜん', en: 'yes, natural' }, { jp: 'いいえ、にんげんが つくった', en: 'no, man-made' }, { jp: 'どちらでも ない', en: 'neither' }],
      correctJp: 'はい、しぜん',
    },
    {
      visual: '🌲',
      q: 'もりは しぜんの もの？',
      qEn: 'Is a forest a natural feature?',
      choices: [{ jp: 'はい、しぜん', en: 'yes, natural' }, { jp: 'いいえ、にんげんが つくった', en: 'no, man-made' }, { jp: 'どちらでも ない', en: 'neither' }],
      correctJp: 'はい、しぜん',
    },
  ],
  pool2: [
    {
      visual: '🏙️',
      q: 'まちより おおきい ところは？',
      qEn: 'A place bigger than a town is a...?',
      choices: [{ jp: 'し（シティ）', en: 'city' }, { jp: 'むら', en: 'village' }, { jp: 'のうじょう', en: 'farm' }],
      correctJp: 'し（シティ）',
    },
    {
      visual: '🏭',
      q: 'こうじょうとは なに？',
      qEn: 'What is a factory?',
      choices: [{ jp: 'ものを つくる ばしょ', en: 'a place where things are made' }, { jp: 'たべものを そだてる ばしょ', en: 'a place where food is grown' }, { jp: 'ふねが とまる ばしょ', en: 'a place where ships stop' }],
      correctJp: 'ものを つくる ばしょ',
    },
    {
      visual: '🚜',
      q: 'のうじょうとは なに？',
      qEn: 'What is a farm?',
      choices: [{ jp: 'たべものを そだてる ばしょ', en: 'where food is grown' }, { jp: 'ものを つくる ばしょ', en: 'where things are made' }, { jp: 'ふねが くる ばしょ', en: 'where ships come' }],
      correctJp: 'たべものを そだてる ばしょ',
    },
    {
      visual: '⚓',
      q: 'みなととは なに？',
      qEn: 'What is a port?',
      choices: [{ jp: 'ふねが はいる ばしょ', en: 'where ships arrive and depart' }, { jp: 'ひこうきが とぶ ばしょ', en: 'where aeroplanes fly from' }, { jp: 'たべものを うる ばしょ', en: 'where food is sold' }],
      correctJp: 'ふねが はいる ばしょ',
    },
    {
      visual: '🏪',
      q: 'みせは にんげんが つくった もの？',
      qEn: 'Is a shop a physical or human feature?',
      choices: [{ jp: 'にんげんの とくちょう', en: 'human feature' }, { jp: 'しぜんの とくちょう', en: 'physical feature' }, { jp: 'どちらでも ない', en: 'neither' }],
      correctJp: 'にんげんの とくちょう',
    },
    {
      visual: '🏔️',
      q: 'やまは どちらの とくちょう？',
      qEn: 'Is a mountain a physical or human feature?',
      choices: [{ jp: 'しぜんの とくちょう', en: 'physical feature' }, { jp: 'にんげんの とくちょう', en: 'human feature' }, { jp: 'どちらでも', en: 'both' }],
      correctJp: 'しぜんの とくちょう',
    },
    {
      visual: '🏠',
      q: 'いえは にんげんが つくった もの？',
      qEn: 'Is a house a physical or human feature?',
      choices: [{ jp: 'にんげんの とくちょう', en: 'human feature' }, { jp: 'しぜんの とくちょう', en: 'physical feature' }, { jp: 'どちらでも ない', en: 'neither' }],
      correctJp: 'にんげんの とくちょう',
    },
    {
      visual: '🏘️',
      q: 'むらは まちより おおきい？',
      qEn: 'Is a village bigger than a town?',
      choices: [{ jp: 'いいえ、むらの ほうが ちいさい', en: 'no, a village is smaller' }, { jp: 'はい、むらの ほうが おおきい', en: 'yes, a village is bigger' }, { jp: 'おなじ おおきさ', en: 'the same size' }],
      correctJp: 'いいえ、むらの ほうが ちいさい',
    },
    {
      visual: '🏙️',
      q: 'まちと むらで おおきいのは？',
      qEn: 'Which is bigger, a town or a village?',
      choices: [{ jp: 'まち', en: 'town' }, { jp: 'むら', en: 'village' }, { jp: 'おなじ', en: 'the same' }],
      correctJp: 'まち',
    },
    {
      visual: '🌊',
      q: 'かわは しぜんの もの？',
      qEn: 'Is a river a physical feature?',
      choices: [{ jp: 'はい、しぜん', en: 'yes, physical' }, { jp: 'いいえ、にんげんが つくった', en: 'no, human-made' }, { jp: 'どちらでも', en: 'both' }],
      correctJp: 'はい、しぜん',
    },
    {
      visual: '🏢',
      q: 'おふぃすとは なに？',
      qEn: 'What is an office?',
      choices: [{ jp: 'ひとが はたらく ばしょ', en: 'where people work' }, { jp: 'たべものを そだてる ばしょ', en: 'where food is grown' }, { jp: 'ふねが とまる ばしょ', en: 'where ships dock' }],
      correctJp: 'ひとが はたらく ばしょ',
    },
    {
      visual: '🏭',
      q: 'こうじょうは しぜんの もの？',
      qEn: 'Is a factory a physical feature?',
      choices: [{ jp: 'いいえ、にんげんが つくった', en: 'no, human-made' }, { jp: 'はい、しぜん', en: 'yes, natural' }, { jp: 'どちらでも', en: 'both' }],
      correctJp: 'いいえ、にんげんが つくった',
    },
  ],
}

// ─── World 2 module registry ──────────────────────────────────────────────────

export const WORLD2_MODULES = [
  { id: 1, titleJp: 'たいりくとうみをおぼえよう', titleEn: 'Continents & Oceans', emoji: '🌍', color: '#4DAAAA', data: m21 },
  { id: 2, titleJp: 'イギリスをしらべよう',       titleEn: 'The UK',               emoji: '🇬🇧', color: '#E8963E', data: m22 },
  { id: 3, titleJp: 'おてんきをしらべよう',       titleEn: 'Weather',              emoji: '🌤️', color: '#6BAF6B', data: m23 },
  { id: 4, titleJp: 'ちけいとまちをしらべよう',   titleEn: 'Landscapes & Towns',   emoji: '🏔️', color: '#D45B5B', data: m24 },
]
